apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  ports:
  - port:  {{.Values.Python.portNumber }}
    protocol: TCP
    targetPort:  {{.Values.Python.portNumber }}
  selector:
    app: backend
status:
  loadBalancer: {}
