apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - port:  {{.Values.React.portNumber }}
    protocol: TCP
    targetPort: {{.Values.React.portNumber }}
  selector:
    app: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
